-- ==============================================================================
-- ⚡ SUPABASE ONE-CLICK SETUP SCRIPT
-- Copy and paste this ENTIRE script into your Supabase SQL Editor and run it.
-- ==============================================================================

-- 1. Create the 'meals' table
create table if not exists meals (
  id bigint generated by default as identity primary key,
  user_id uuid default auth.uid(), -- Automatically sets to current user (including anon)
  image_before text,
  image_after text,
  score integer,
  analysis text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. Enable Security (RLS)
alter table meals enable row level security;

-- 3. Create Policies for the 'meals' table
-- Allow anyone (including anonymous) to Create meals
create policy "Allow all users to create meals" 
on meals for insert 
with check (true);

-- Allow users to View their own meals
create policy "Allow users to view own meals" 
on meals for select 
using ( (select auth.uid()) = user_id );

-- 4. Create the Storage Bucket ('meal-images')
-- This inserts directly into the storage.buckets table
insert into storage.buckets (id, name, public)
values ('meal-images', 'meal-images', true)
on conflict (id) do nothing;

-- 5. Create Policies for Storage
-- Allow public access to view images
create policy "Give public access to meal-images"
on storage.objects for select
using ( bucket_id = 'meal-images' );

-- Allow anyone (anon + auth) to upload images
create policy "Allow uploads to meal-images"
on storage.objects for insert
with check ( bucket_id = 'meal-images' );

-- ==============================================================================
-- ✅ SETUP COMPLETE
-- ==============================================================================
